### ISSUE TITLE
Check if SD Files need to be updated

### ISSUE THREAD

**Issue by xawox** [BCN3D/BCN3D-Cura-Windows#1]
When upload the firmware by cura, it should be useful have an alert if it's needed to change the sd files or  copy the files in a selected device. Maybe it should check if there is the .zip file or something.

**Comment by xawox** [comment]
Also it should show the news of the new version of Firmware, i don't know where to put the data ;)

**Comment by kitusmark** [comment]
in the latest release 1.1.4 when you do a check for firmware update in the windows shows some info about SD files.
