### ISSUE TITLE
Critical Issue: Old Sigma FW get's installed with "install default firmware" which could damage the printer.

### ISSUE THREAD

**Issue by mrcg** [BCN3D/BCN3D-Cura-Windows#11]
The Sigma FW which is packaged in the latest Cura version v0.1.4 is very old.
When pusing the "install default firmware" in Cura v0.1.4 this FW will be uploaded to Sigma controller.
With this FW the Sigma is not homing the left extruder (micro swithc) correctly what is needed for the bed (z-axis) homing. This could cause the z-homing not to stop and break the glass on heating bed.

The packaged Sigma FW should always contain the latest firmware version!!!

**Comment by remelbourne** [comment]
@mrcg We deleted that option in the new version
