### ISSUE TITLE
Improper motion

### ISSUE THREAD

**Issue by anfonee1** [BCN3D/BCN3D-Cura-Windows#18]
Machine would lose calibration as others are reporting after a long period of being powered down.  Now when I go to calibrate all motions move quicker than they should and long 3-5 minute processing pauses after each calibration step.  Machine makes weird sound during these pauses like a repetitive purr with and click. Any way to hard reset?

**Comment by remelbourne** [comment]
@anfonee1 Please take a look at this page https://github.com/BCN3D/BCN3DSigma-Firmware/issues in case someone has already commented on this issue or if it has been fixed.
