### ISSUE TITLE
More Info on the Firmware update screen

### ISSUE THREAD

**Issue by kitusmark** [BCN3D/BCN3D-Cura-Windows#2]
It would be nice if on the Upgrade BCN3D Sigma Firmware screen were some information of the BCN3DSigma Folder created when downloading the files from github. Adding a Info icon or something would be nice too!

 Also I think the folder should be called BCN3D, because is not only for the Sigma 3D Printer.

![captura](https://cloud.githubusercontent.com/assets/6075056/10363898/ad67b81c-6db7-11e5-9ba4-ec2f36994000.PNG)

For example:

> **_Cura BCN3D is going to download the required files from github.com and is going to store then in >your hard drive under C:/Users/Documents.... the folder will be called BCN3D and there you can find >the source code for the firmwares as well the compiled version.**_

**Comment by remelbourne** [comment]
Done!
