### ISSUE TITLE
Linux version?

### ISSUE THREAD

**Issue by philippejadin** [BCN3D/BCN3D-Cura-Windows#24]
The title says it all :-)

Is it possible to download the official cura linux edition and download the bcn3d settings separately? This in the long run would be the best model for you to keep up to date with dev, imho.

**Comment by kitusmark** [comment]
Hi @philippejadin 

I totally agree with you. We've been developing features for the Cura 15 version for quite a long now and all of those features will be unsupported when Cura 2 leave beta. 

So developing an installation package that installs stuff over Cura (any version/platform) will be the real deal. 

Thanks for the feedback!

**Comment by philippejadin** [comment]
Of course, depending on the relationship between ultimaker and bcn3d (or to be more precise, the openess of ultimaker to features they don't support in their own hardware), it would be best to submit pull requests directly to ultimaker's cura repository.

Maybe I'm dreaming here :-)

**Comment by Zorgonaute84** [comment]
I'm working on a BCN3D Sigma profil (json for the printer and for the extruders). I can share it when it will be done (nothing too complex, but I havn't a lot of time for the moment). With this profil it's very easy to add a new printer with all the parameters of the Sigma into Cura 2.

I saw on the Ultimaker forum that developpers are open to include natively in Cura custum printer. We just have to send us the json profil. Maybe BCN3D could share this king of profil with them to implemant the Sigma support into Cura for long time.

**Comment by kitusmark** [comment]
Hi @Zorgonaute84 

We're currently working on that too. You can see it here... 
https://github.com/BCN3D/BCN3D-Utilities/tree/master/Cura%202%20BCN3D%20Profiles

Any contributions will be appreciated.

Thanks!

**Comment by benoit-cty** [comment]
Hello, any news on this issue ?
Where is the place to look up for fresh update ?
I have a Sigma R17 and Ubuntu 16.04.
Making Open Source Hardware that have to be used with Proprietary Software is quite strange.

**Comment by guillemap** [comment]
We will release a linux version for our new Cura project. You can check the development [here](https://github.com/BCN3D/Cura)
