### ISSUE TITLE
2nd extruder as main and first as support material

### ISSUE THREAD

**Issue by Dr-3D** [BCN3D/BCN3D-Cura-Windows#26]
I constantly change materials on my bcn3d sigma, and I wonder if it is possible to use the second extruder as main and the first extruder as material support

**Comment by guillemap** [comment]
Hello, by now Cura doesn't support that feature, but you can use one of this two workarounds:

1. Use our [Extruder Inverter plugin](https://github.com/BCN3D/Extruder-Inverter-Plugin) when generating the GCode, which does exactly what you suggest.
2. If you already have the GCode, just open it with a text editor and replace all `T0` to `T1`, and `T1` to `T0`.

Hope it helps!

**Comment by Dr-3D** [comment]
It work! I appreciated a lot, thank you

**Comment by guillemap** [comment]
You're welcome!
