### ISSUE TITLE
Check for firmware updates improvements

### ISSUE THREAD

**Issue by kitusmark** [BCN3D/BCN3D-Cura-Windows#9]
Hi @remelbourne 

I've noticed a couple of things in the _"check for firmware updates"_ menu. 
- It only works once. When you complete the process and you try to go again to the menu option it doesn't do anything.
- In the last step of the process **"Finish"** button doesn't do anything too. It should close the window normally.

**Comment by remelbourne** [comment]
Thank you Marc! I'll take a look at it

2016-03-03 3:58 GMT-08:00 Marc notifications@github.com:

> Assigned #9 https://github.com/BCN3D/BCN3D-Cura-Windows/issues/9 to
> @remelbourne https://github.com/remelbourne.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/BCN3D/BCN3D-Cura-Windows/issues/9#event-576135349.

## 

Rebeca Melbourne
Àrea de R+D+i
http://www.reprapbcn.com/ http://www.facebook.com/reprapbcn/
http://www.twitter.com/reprapbcn http://www.youtube.com/user/reprapbcn

Nova Edició 2015 del Programa de Màster i Postgrau. Vine a les sessions
informatives:
Disseny i fabricació de Producte
http://www.fundaciocim.org/formacio/mipg/master-en-enginyeria-i-produccio-integrades-ordinador
- Automatització http://www.fundaciocim.org/ca/formacio/master-pair
- Direcció
  de la Producció
  http://www.fundaciocim.org/content/master-en-direccio-de-la-produccio

**Comment by remelbourne** [comment]
Fixed!
